### ISSUE TITLE
Issue with git submodule update on CentOS

### ISSUE THREAD

**Issue by pulpfree** [iriscouch/build-couchdb#16]
On a local CentOS distribution, then running: 
git clone git://github.com/iriscouch/build-couchdb
cd build-couchdb
git submodule init
git submodule update

I get this error: 
fatal: unable to write new index file
Unable to checkout 'b6dc1a844eab061d0a7153d46e7e68296f15a504' in submodule path 'dependencies/otp'

Any help is appreciated.

ron

**Comment by pulpfree** [comment]
Found issue, apparently after a lengthy script I ran out or HD space.

**Comment by jhs** [comment]
Cool. Good luck with your project!
