### ISSUE TITLE
CouchDB's github repository is obsolete

### ISSUE THREAD

**Issue by marcenuc** [iriscouch/build-couchdb#18]
It look like the github mirror is not updated anymore.
From CouchDB home page the new repository is at http://git-wip-us.apache.org/repos/asf/couchdb.git
Taken from http://couchdb.apache.org/community/code.html

**Comment by jhs** [comment]
Right. I changed to that repository last October in 4282959c

**Comment by marcenuc** [comment]
OK, I've just learned that `git submodule update` is not enough to update the submodules.

Sorry for the spam.
