### ISSUE TITLE
Tracking CouchDB 1.2

### ISSUE THREAD

**Issue by nanodeath** [iriscouch/build-couchdb#24]
Any plans to support CouchDB 1.2?  Simply running rake git="...official 1.2.x repo tag..." results in https://gist.github.com/1482481

**Comment by jhs** [comment]
That's interesting. Yes, I plan to support CouchDB 1.2 however I do not think it is close to a release yet. At least, I haven't seen any serious discussion on the mailing list.

Of course, the work must be done at some point, so might as well start now. I investigate what's going on.

**Comment by nanodeath** [comment]
It's not that urgent, but tools like RVM let you build the latest edge version of various versions of Ruby...would be nice if this let you do the same thing for Couch :)

Actually, more specifically I was interested in measuring the speedups from https://issues.apache.org/jira/browse/COUCHDB-1334

**Comment by jhs** [comment]
Yes that is what build-couchdb does, it's just a bug that it doesn't support 1.2. People have used it to build trunk/master builds in the past though, which is the goal.

**Comment by jhs** [comment]
Okay, I fixed the autotools errors and I think it works now. You can either use the master branch with the `git="..."` option, or there is a "1.2" branch which is bound to the ASF CouchDB 1.2.x branch. (Mind your git submodule inits and updates, as always.)

**Comment by jhs** [comment]
Pretty sure this is resolved.
