### ISSUE TITLE
Move installation

### ISSUE THREAD

**Issue by soitgoes** [iriscouch/build-couchdb#3]
Currently it appears that everything hardcodes the pathing during the build process.  So you can't move the build.   It has to be where you want it to live forever before you build it.

**Comment by jhs** [comment]
Yes, that is because nearly every single sub-project which Build CouchDB builds is doing that too. Therefore the answer is to get them all relocatable upstream, which is sort of daunting.

The workaround is to specify where you want to install at build time.

```
rake install=/path/where/I/want/couchdb
```
