### ISSUE TITLE
rpm package for a CouchDB version for production boxes

### ISSUE THREAD

**Issue by sanchitbahal** [iriscouch/build-couchdb#32]
Is there a way I can create an rpm package for a particular CouchDB version? I do not want to pollute my production box with all the dev-related (e.g., compiler) stuff.

Or is there any alternate mechanism?

Thanks,
Sanchit Bahal

**Comment by jhs** [comment]
Sure, the `install=` option to Rake will tell build-couchdb where to put all the final files. You can package that up using whatever tools you like, then install it on any similar computer. One note, though: when CouchDB compiles, it hard-codes some of those paths into its programs; thus, you need to install the CouchDB directory to the same location on every computer.
