### ISSUE TITLE
How to build version 1.1.x

### ISSUE THREAD

**Issue by ghost** [iriscouch/build-couchdb#36]
Hello,

   From the READ.md file, it is not clear to me on how to build a specific version of the Couchdb.
   My second problem is how to run multiple Couchdb instances on the same machine.

Thanks,
Alex

**Comment by jhs** [comment]
Hi, That is accomplished using the `git=` option. Specify the URL for the repository and also the tag name, such as `1.1.1`.

To run multiple instances, just execute CouchDB multiple times, with different config files (with the listen port configured differently).

**Comment by ghost** [comment]
I noticed that you are using the "https://git-wip-us.apache.org/repos/asf/couchdb.git" server.
Not the "https://github.com/apache/couchdb.git" server. That's why I was giving it the wrong branch name.
Is there any reason you don't use the github server?

Thanks for your response!
Alex

**Comment by jhs** [comment]
Yes, I am trying to use the official sources for the software.
On Feb 29, 2012 10:40 PM, "akatebi" <
reply@reply.github.com>
wrote:
