### ISSUE TITLE
Using build-couchdb to install couchdb on servers?

### ISSUE THREAD

**Issue by kikito** [iriscouch/build-couchdb#37]
Hi,

Is it possible/advisable to use build-couchdb in a staging/production server?

If so, what does one have to change in the installation steps so that it works like any other DBMS? I'm particularly interested on  starting up couchdb automatically on server boot, and being installed in a "proper" folder - not /home/billy/ 

I somehow doubt this can be accomplished by simply doing `sudo rake` instead of `rake` :)

Regards,

Enrique

**Comment by jhs** [comment]
The key point to remember is that the build-couchdb `rake` command is really a wrapper around `./configure && make install`.

Firstly, you can simply run `rake install=/usr/local` and that will internally run `./configure --prefix=/usr/local` for all components. Or you might install to /usr/local/software and then use GNU Stow.

Getting CouchDB hooked into the boot process is currently out of scope for build-couchdb (hence its name) and is OS and distribution-specific. For example, the [Installing on Ubuntu](http://wiki.apache.org/couchdb/Installing_on_Ubuntu) page is helpful (particularly where it gets into /etc/init.d stuff).

**Comment by kikito** [comment]
Alright, understood. I was hoping to skip the Installing On Ubuntu steps and the /etc/init.d stuff, but I guess I will not.

Thanks for your feedback and your project!
