### ISSUE TITLE
Ubuntu 11.10 64 server not install [bug]

### ISSUE THREAD

**Issue by gabrielmancini** [iriscouch/build-couchdb#39]
c++ -o jsinterp.o -c  -I./dist/system_wrappers_js -include /root/build-couchdb/dependencies/spidermonkey/js/src/config/gcc_hidden.h -DOSTYPE=\"Linux2.6\" -DOSARCH=Linux -DEXPORT_JS_API -DIMPL_MFBT -D__STDC_LIMIT_MACROS  -I/root/build-couchdb/dependencies/spidermonkey/js/src -I. -I./dist/include -I./dist/include/nsprpub     -I/root/build-couchdb/dependencies/spidermonkey/js/src -I/root/build-couchdb/dependencies/spidermonkey/js/src/assembler -I/root/build-couchdb/dependencies/spidermonkey/js/src/yarr  -fPIC  -fno-rtti -fno-exceptions -Wall -Wpointer-arith -Woverloaded-virtual -Wsynth -Wno-ctor-dtor-privacy -Wno-non-virtual-dtor -Wcast-align -Wno-invalid-offsetof -Wno-variadic-macros -Werror=return-type -pedantic -Wno-long-long -fno-strict-aliasing -pthread -pipe  -DNDEBUG -DTRIMMED -g -O3 -fstrict-aliasing -fno-stack-protector -fomit-frame-pointer -DUSE_SYSTEM_MALLOC=1 -DENABLE_ASSEMBLER=1 -DENABLE_JIT=1   -DMOZILLA_CLIENT -include ./js-confdefs.h -MD -MF .deps/jsinterp.pp /root/build-couchdb/dependencies/spidermonkey/js/src/jsinterp.cpp
In file included from /root/build-couchdb/dependencies/spidermonkey/js/src/jsinterp.cpp:85:0:
/root/build-couchdb/dependencies/spidermonkey/js/src/jsobjinlines.h: In member function ‘void JSObject::setArrayLength(uint32)’:
/root/build-couchdb/dependencies/spidermonkey/js/src/jsobjinlines.h:367:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
In file included from /root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssembler.h:54:0,
                 from /root/build-couchdb/dependencies/spidermonkey/js/src/methodjit/MonoIC.h:44,
                 from /root/build-couchdb/dependencies/spidermonkey/js/src/jsinterp.cpp:102:
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h: In member function ‘JSC::AbstractMacroAssemblerJSC::X86Assembler::Call JSC::MacroAssemblerX86_64::call()’:
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h:127:22: warning: variable ‘label’ set but not used [-Wunused-but-set-variable]
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h: In member function ‘JSC::AbstractMacroAssemblerJSC::X86Assembler::Call JSC::MacroAssemblerX86_64::tailRecursiveCall()’:
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h:135:22: warning: variable ‘label’ set but not used [-Wunused-but-set-variable]
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h: In member function ‘JSC::AbstractMacroAssemblerJSC::X86Assembler::Call JSC::MacroAssemblerX86_64::makeTailRecursiveCall(JSC::AbstractMacroAssemblerJSC::X86Assembler::Jump)’:
/root/build-couchdb/dependencies/spidermonkey/js/src/assembler/assembler/MacroAssemblerX86_64.h:144:22: warning: variable ‘label’ set but not used [-Wunused-but-set-variable]
{standard input}: Assembler messages:
{standard input}:26529: Warning: end of file not at end of a line; newline inserted
{standard input}:28246: Error: unknown pseudo-op: `.lbe25070'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[1]: Leaving directory`/tmp/tracemonkey_build20120309-22228-1tkrui3'
make[1]: **\* [jsinterp.o] Error 4
make: **\* [default] Error 2
git checkout HEAD configure.in
git clean -df .
rake aborted!
Command failed with status (2): [make ...]
/usr/lib/ruby/1.8/rake.rb:995:in `sh'
/usr/lib/ruby/1.8/rake.rb:1010:in`call'
/usr/lib/ruby/1.8/rake.rb:1010:in `sh'
/usr/lib/ruby/1.8/rake.rb:1094:in`sh'
/root/build-couchdb/tasks/lib.rb:142:in `gmake'
/root/build-couchdb/tasks/tracemonkey.rake:45
/root/build-couchdb/tasks/tracemonkey.rake:28:in`chdir'
/root/build-couchdb/tasks/tracemonkey.rake:28
/usr/lib/ruby/1.8/tmpdir.rb:129:in `mktmpdir'
/root/build-couchdb/tasks/tracemonkey.rake:27
/usr/lib/ruby/1.8/rake.rb:636:in`call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in`each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in`each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in`each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in`each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in`each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in`invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in`each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in`run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in`run'
/usr/bin/rake:28

**Comment by jhs** [comment]
Interesting. Would you please post your entire rake.log file in gist or pastebin? Thanks.

**Comment by gabrielmancini** [comment]
now i try to install on debian and other err. 
the log is in gist file https://gist.github.com/2065816

**Comment by gabrielmancini** [comment]
there is no a stable version of the builder, i try the master branch and 1.2 and the tag 0.10 on debian and ubuntu.
awes same error...

**Comment by gabrielmancini** [comment]
now other error
git submodule update
Cloning into dependencies/couchdb...
Fatal: no entropy gathering module detected
Clone of 'https://git-wip-us.apache.org/repos/asf/couchdb.git' into submodule path 'dependencies/couchdb' failed

**Comment by jhs** [comment]
Hi. "No entropy gathering module detected" is an unrelated issue. It seems like it is related to using a virtual server such as Xen.

**Comment by gabrielmancini** [comment]
jhs, and other errors? 
do you know how i need proced in this case using Xen?
