### ISSUE TITLE
In Ubuntu 11.04, libmozjs185-dev package must be removed.

### ISSUE THREAD

**Issue by marcenuc** [iriscouch/build-couchdb#4]
Reporting it here to be sure it does not get lost.
On Ubuntu 11.04, the build does fail if the libmozjs185-dev package is installed. Removing it, solves the problem.

Reported by Daniel Itaborai at
http://mail-archives.apache.org/mod_mbox/couchdb-user/201109.mbox/%3CCALxWR-mJksbr7R=PFntwTnYsMgizU-w=E5nZHGJwYyCZkk9GCg@mail.gmail.com%3E

**Comment by jhs** [comment]
Whew, I think I solved this. The "ubuntu" branch has the likely fix. I will promote it to the master branch when I confirm that the code works on the other platforms.

**Comment by marcenuc** [comment]
Thanks Jason.
Today, for the first time ever, I was able to build CouchDB and run ALL the tests from Futon without errors from start to finish.
Thank you.

**Comment by jhs** [comment]
Cool!
