### ISSUE TITLE
Build on OS X Snow Leopard

### ISSUE THREAD

**Issue by ryanramage** [iriscouch/build-couchdb#5]
After building, and trying to run couchdb on 10.6.8 I get this error:

```
initial call: application_master:init/4
pid: <0.30.0>
registered_name: []
exception exit: {bad_return,
                    {{couch_app,start,
                         [normal,
                          ["/Users/ryan/devel/build-couchdb/build/etc/couchdb/default.ini",
                           "/Users/ryan/devel/build-couchdb/build/etc/couchdb/local.ini"]]},
                     {'EXIT',
                         "dlopen(/Users/ryan/devel/build-couchdb/build/lib/couchdb/erlang/lib/couch-1.1.0/priv/lib/couch_icu_driver.so, 2): no suitable image found.  Did find:\n\t/Users/ryan/devel/build-couchdb/build/lib/couchdb/erlang/lib/couch-1.1.0/priv/lib/couch_icu_driver.so: mach-o, but wrong architecture"}}}
```

I am sure it has to do with this

http://comments.gmane.org/gmane.comp.db.couchdb.user/6326

Not sure how to get the proper erlang and icu flags set in the build-couchdb script.

**Comment by jhs** [comment]
That's weird. You must be on a 64-bit machine, right? Are you running older code or the latest commit? Maybe I introduced an error recently. When I say "supports OS X" I unfortunately really mean "supports Jason's laptop" until such time as I set up a build farm.

Anyway, this is the commit: https://github.com/iriscouch/build-couchdb/commit/96ec5549cc368008eabc63487c2c8eee44c9bcd0

What is the output on your mac of this command?

```
sysctl -n hw.machine
```

Also, if you run `irb` in the terminal, what is the output of this?

```
`sysctl -n hw.machine`.chomp.inspect
```

After you respond, perhaps you can hard-code that value about the 64-bit stuff, either enabled or disabled.

**Comment by jhs** [comment]
Hm, on second thought, that might be a red-herring since your problem is the icu driver, not anything in the Erlang build. Still thinking...

**Comment by ryanramage** [comment]
sysctl -n hw.machine returns i386 on my machine, but it's still 64 bit. 

See here for other examples to detect 64 bit arch:
http://yourmacguy.wordpress.com/2008/10/08/archbits/
http://stackoverflow.com/questions/1365189/detect-64-bit-cpu-in-ruby-on-mac-os-x

Have not had a chance yet to rerun the compile with the flag changed by hand. I will let you know results.

**Comment by jhs** [comment]
Thanks for the update and the tip. What kind of Mac are you on?

Would you please run this Ruby one-liner and paste the exact output? If this is the problem, we need to find a common result so we can redefine "supports OS X" to mean "supports both Jason and Ryan's mac".

**Edit** more explicit output.

```
ruby -e 'puts %x[ /usr/sbin/sysctl -n hw.optional.x86_64 2>/dev/null ].chomp.inspect; puts $?.success?.inspect'
```

My output looks like this:

```
$ ruby -e 'puts %x[ /usr/sbin/sysctl -n hw.optional.x86_64 2>/dev/null ].chomp.inspect; puts $?.success?.inspect'
"1"
true
```

**Comment by ryanramage** [comment]
$ ruby -e 'puts %x[ /usr/sbin/sysctl -n hw.optional.x86_64 2>/dev/null ].chomp.inspect; puts $?.success?.inspect'
"1"
true

Seems to be the same. I am on a MacBook Pro circa 2008. Processor 2.4 GHx Intel Core 2 Duo. I have mainly started using it to get mac/win support for couchapp-takeout and http://eckoit.com. Anyway, if this works your supports OSX userbase will be very grateful :)

**Comment by jhs** [comment]
@ryanramage, would you please pull and let me know if it builds.

```
rm -rf ./build
rake # You know the drill :)
```

**Comment by ryanramage** [comment]
worked perfect. thanks!
