### ISSUE TITLE
Error when building on CentOS 5.5 during Curl build

### ISSUE THREAD

**Issue by pgelinas** [iriscouch/build-couchdb#55]
I'm trying to build couchdb on a CentOS 5.5 and it doesn't work (wouldn't be here if it did heh? :) )

By digging in the rake.log, I'm able to see some "problems"; I don't know if they're fatal or not, but the last one I assume is since that's where it fails. Here's the STDERR output from the rake.log (interwoven in STDOUT)

STDOUT buildconf: running autoconf
STDERR configure.ac:195: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
STDERR       If this token and others are legitimate, please use m4_pattern_allow.
STDERR       See the Autoconf documentation.
STDERR configure.ac:221: error: possibly undefined macro: AC_PROG_LIBTOOL
STDOUT The autoconf command failed

STDERR env LDFLAGS='-Xlinker -rpath=/usr/local/build-couchdb/build/lib -L/usr/local/build-couchdb/build/lib' CPPFLAGS='-I/usr/local/build-couchdb/build/include -I/usr/local/build-couchdb/build/include/js' /usr/local/build-couchdb/dependencies/curl/configure --prefix='/usr/local/build-couchdb/build' --with-js-include='/usr/local/build-couchdb/build/include/js' --with-js-lib='/usr/local/build-couchdb/build/lib' --with-erlang=/usr/local/build-couchdb/build/lib/erlang/usr/include

STDERR /usr/local/build-couchdb/dependencies/curl/configure: line 8452: AC_LIBTOOL_WIN32_DLL: command not found
STDERR /usr/local/build-couchdb/dependencies/curl/configure: line 8482: AC_PROG_LIBTOOL: command not found

STDERR configure: WARNING: Cannot find libraries for LDAP support: LDAP disabled

STDERR config.status: error: cannot find input file: Makefile.in
STDERR cat config.log

[bunch of "STDOUT configure: failed program was:" output]

STDERR git ls-files --others --ignored --exclude-standard | xargs rm || true
STDERR rake aborted!
STDERR Command failed with status (1): [env LDFLAGS='-Xlinker -rpath=/usr/local/bu...]

Seems it is complaining that libtool isn't installed... but it is. I might of missed something, so the full log is available by e-mail on request.

Any help is appreciated.
Thanks.

**Comment by jlank** [comment]
I'm experiencing the a similar issue trying to install on CentOs 5.8

```
...
#define HAVE_STDIO_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define USE_MANUAL 1
#define NTLM_WB_ENABLED 1
#define NTLM_WB_FILE "/usr/bin/ntlm_auth"

configure: exit 1
== End of config.log ==
rm_f /data01/couchdb-1.2//bin/autoconf
rm_f /data01/couchdb-1.2//bin/autoreconf
rm_f /data01/couchdb-1.2//bin/autoheader
rm_f /data01/couchdb-1.2//bin/autom4te
rake aborted!
Command failed with status (1): [env LDFLAGS='-Xlinker -rpath=/data01/couch...]

Tasks: TOP => default => couchdb:build => couchdb:couchdb => curl:build => /data01/couchdb-1.2//bin/curl
(See full trace by running task with --trace)
```

**Comment by pfiled** [comment]
I'm not sure how to link it to this issue, but I fixed this problem by building libtool as dependency. That gets the m4 macros in place that are needed, and the build proceeds. I opened a pull request for it: https://github.com/iriscouch/build-couchdb/pull/67

Please test it out and let us know how it goes.

**Comment by pgelinas** [comment]
I'm no longer responsible for the CouchDb setup and the new mechanism in place does not use this module, so I can't test it.
