### ISSUE TITLE
Install multiple versions side-by-side

### ISSUE THREAD

**Issue by tivolix** [iriscouch/build-couchdb#6]
Attempt to install multiple versions of CouchDB.

Command used:
rake git="git://git.apache.org/couchdb.git tags/0.10.0" \
install=/path/to/couchdb/dependencies \
couchdb_build=/path/to/couchdb/0.10.0

Failed with "rake aborted!" Here is the result rake.log: https://gist.github.com/1226942
Operating system: Ubuntu 10.04

**Comment by jhs** [comment]
Hi! I think the error begins at line 1172: https://gist.github.com/1226942#L1172

Despite the documentation, I do not actually recall ever building CouchDB version 0.10. It is possible that the included Javascript is incompatible.

If you clean and rebuild everything except using `tags/0.11.0` does it complete successfully?

If so, I will add an older Spidermonkey for older builds. Thanks!

**Comment by tivolix** [comment]
Tried with tags 0.11.2 and upward and everything works just fine, however tag 0.11.0 failed also. Thanks for the hint.
I think the issue is now resolved, the problem seems with older versions of CouchDB only.
