### ISSUE TITLE
Install help2man

### ISSUE THREAD

**Issue by daschl** [iriscouch/build-couchdb#61]
Hi,

I've been using your guides to install couchdb but on ubuntu is the "help2man" package missing. From other ticket I see this is a n issue on centos too.

Can you include it in your readme file installation instructions?

Thanks,
Michael

**Comment by thedod** [comment]
just happened to me, and `apt-get install help2man` solved it. I guess it's a README fix, yet it's not pleasant when a rake breaks, so it's an _important_ README fix ;)

**Comment by jhs** [comment]
I am currently quite unhappy with the way build-couchdb does packages. Half of them, it simply recommends that you install them yourself (bad). For the other half, it automatically installs them itself using sudo (worse).

**Comment by thedod** [comment]
Maybe best is to have everything in the README, and the script should check in the beginning that eveything's there, and if not - say _"X, Y and Z are not installed. see README"_ and abort (like the message I get when I forget to init+update submodules).

**Comment by jhs** [comment]
Yes, that is exactly what I would prefer. In the meantime I will simply
update the README.

On Wed, Sep 5, 2012 at 1:15 PM, Nimrod S. Kerrett
notifications@github.comwrote:

> Maybe best is to have everything in the README, and the script should
> check in the beginning that eveything's there, and if not - say _"X, Y
> and Z are not installed. see README"_ and abort (like the message I get
> when I forget to init+update submodules).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iriscouch/build-couchdb/issues/61#issuecomment-8288667.

## 

Iris Couch
