### ISSUE TITLE
Unable to clone couchdb

### ISSUE THREAD

**Issue by afshin2003** [iriscouch/build-couchdb#69]
Hi Guys,
I have tried both https & git to clone couchdb : 

BY HTTPS 

Initialized empty Git repository in /opt/build-couchdb/dependencies/couchdb/.git/
error:  while accessing https://git-wip-us.apache.org/repos/asf/couchdb.git/info/refs

fatal: HTTP request failed
Clone of 'https://git-wip-us.apache.org/repos/asf/couchdb.git' into submodule path 'dependencies/couchdb' failed

BY GIT

Initialized empty Git repository in /opt/build-couchdb/dependencies/couchdb/.git/
git-wip-us.apache.org[0: 140.211.11.121]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Clone of 'git://git-wip-us.apache.org/repos/asf/couchdb.git' into submodule path 'dependencies/couchdb' failed

BEST,
Afshin

**Comment by jhs** [comment]
That is odd. I think you may want to tell the Apache CouchDB project about this.

(It could also have been transient downtime.)

**Comment by afshin2003** [comment]
Hi jhs,
I found the problem ! This is about to verifying SSL certificate in my machine !
I could check out by : 
env GIT_SSL_NO_VERIFY=true git submodule update

:)
