### ISSUE TITLE
Ubuntu 11.04

### ISSUE THREAD

**Issue by s3u** [iriscouch/build-couchdb#7]
rake fails trying to install libcap2-bin on Ubuntu 11.04.

The work-around is to manually download the .deb from from https://launchpad.net/ubuntu/natty/i386/libcap2-bin/1:2.20-1, do an apt-get install, and then run rake.

**Comment by jhs** [comment]
I just re-ran a build and had no problems with the install of libcap2-bin. Do you think it could be a transient error with the repository?

I am testing on an amd64 machine, could it be an i386 thing?

(I am trying to close out old issues. Please feel free to reopen this if you still have a problem. Also, please attach or paste somewhere the rake.log file so I can see what's going on. Thanks!)

**Comment by s3u** [comment]
I have not retried it since I have a working installation for now. Thanks for the reply.
