### ISSUE TITLE
missing package: ruby? But I have it...

### ISSUE THREAD

**Issue by panosru** [iriscouch/build-couchdb#73]
Hello, I try to install couchdb on a debian 6 machine but when I run rake I get the following:

```
[master] #> rake
Build CouchDB commit: 862e8f50f2b779255847e2cba5c1be74505c1ca0
##
## Missing package: ruby
##
## Try: sudo apt-get -y install ruby
##
rake aborted!
Missing package: ruby
/usr/src/build-couchdb/tasks/lib.rb:160:in `block in install_packages'
/usr/src/build-couchdb/tasks/lib.rb:177:in `call'
/usr/src/build-couchdb/tasks/lib.rb:177:in `block in install_packages'
/usr/src/build-couchdb/tasks/lib.rb:176:in `each'
/usr/src/build-couchdb/tasks/lib.rb:176:in `install_packages'
/usr/src/build-couchdb/tasks/all.rake:41:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => default => couchdb:build => couchdb:couchdb => erlang:build => build:os_dependencies => build:debian_dependencies
(See full trace by running task with --trace)

root @ dev2 (0) : /usr/src/build-couchdb

[master] #> rake --version; ruby -v; gem --version
rake, version 10.0.3
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-linux]
2.0.2
```

as you can see I have ruby properly install along with rake and gem via RVM.

Any help would be appriciated! Thanks a lot!

**Comment by jhs** [comment]
Hi.

Yes, I think this crude test does not confirm RVM.

The whole package detection system is bad. I want to remove it. But for now, I simply removed the dependency on the "ruby" package. I want to remove the whole thing; however I do not know how many people these prompts have helped. For all I know, it saves people's bacon.

Anyway, I believe the latest master should work for you. Note, the Git submodule for CouchDB requires an update.

Please let me know if the issue persists. Thanks.
